spring:
  jpa.show-sql: true
  flyway:
    enabled: true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    locations: classpath:db/migration
    baseline-on-migrate: true

cache:
  time-to-live-hours:
    genre: 4
    session: 2
    currency-rates: 2

service.path.nbu: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange