spring:
  datasource.driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    enabled: true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate:
      format_sql: true
