spring:
  datasource.driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  datasource:
    url: jdbc:postgresql://localhost:5432/
  flyway:
    enabled: true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      format_sql: true
      dialect :  org.hibernate.dialect.MySQL5Dialect
